### ISSUE TITLE
No stdout

### ISSUE THREAD

**Issue by chrisgorgo** [bids-apps/brainiak-srm#8]
The App does not produce anything on stdout even if everything goes well. It's not a big deal, but lack of any output makes it hard to debug.

**Comment by mihaic** [comment]
What would you like to see output to stdout?

**Comment by chrisgorgo** [comment]
It seems there are two steps in the code: masking and applying the functional alignemnt. A couple of simple print statements announcing each step would help figuring out what is going on.
